modules:
  enabled:
    - WPLoader
  config:
    WPLoader:
      wpRootFolder: "%WP_FOLDER%"
      dbName: "%DB_NAME%"
      dbHost: "%DB_HOST%"
      dbUser: "%DB_USER%"
      dbPassword: "%DB_PASSWORD%"
      tablePrefix: "%DB_TABLE_PREFIX%"
      domain: "%WP_DOMAIN%"

