paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support

extensions:
  enabled:
    - Codeception\Extension\RunFailed
  commands:
    - "Codeception\\Command\\GenerateWPUnit"

error_level: E_ALL

